"""CLI entry point for the WIT host bindgen.

Usage:
    python -m wasmtime.component.bindgen <wit-path> -o <out-dir>

Drives ``wasm-tools component wit --json``, parses the result into the typed
IR, and emits a Python *package* (one module per WIT interface plus an
``__init__.py`` that re-exports world-level types).

``-o`` is the output directory; it will be created if missing.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from . import _emit, _ir


def _dump_wit_ir(wit_path: Path) -> dict:
    result = subprocess.run(
        ["wasm-tools", "component", "wit", "--json", str(wit_path)],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m wasmtime.component.bindgen",
        description="Generate wasmtime-py wire-shape Python types from a WIT package.",
    )
    parser.add_argument("wit_path", type=Path, help="Path to a WIT directory or file.")
    parser.add_argument(
        "-o", "--output", type=Path, required=True,
        help="Output directory for the generated package.",
    )
    args = parser.parse_args(argv)

    if not args.wit_path.exists():
        print(f"error: WIT path does not exist: {args.wit_path}", file=sys.stderr)
        return 1

    try:
        ir_json = _dump_wit_ir(args.wit_path)
    except FileNotFoundError:
        print("error: wasm-tools binary not found in PATH", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print(f"error: wasm-tools failed:\n{exc.stderr}", file=sys.stderr)
        return 1

    ir = _ir.load(ir_json)
    files = _emit.emit_package(ir)

    out_dir: Path = args.output
    out_dir.mkdir(parents=True, exist_ok=True)
    # Wipe everything under the output root so deletions in the WIT propagate.
    for stale in out_dir.rglob("*.py"):
        stale.unlink()
    for stale_dir in sorted(out_dir.glob("*/"), reverse=True):
        if stale_dir.is_dir() and not any(stale_dir.iterdir()):
            stale_dir.rmdir()

    package_dirs: set[Path] = set()
    for mod_name, content in files.items():
        # Dotted names like ``strands_agent.streaming`` become nested dirs.
        parts = mod_name.split(".")
        target = out_dir.joinpath(*parts[:-1], f"{parts[-1]}.py")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        # Track package dirs that need an __init__.py.
        for i in range(1, len(parts)):
            package_dirs.add(out_dir.joinpath(*parts[:i]))

    # Drop a minimal __init__.py into each subpackage directory that doesn't
    # already have one (the top-level out_dir's __init__ comes from emit_package).
    for pkg_dir in package_dirs:
        init_file = pkg_dir / "__init__.py"
        if not init_file.exists():
            init_file.write_text(
                '"""Auto-generated by bindgen. Do not edit."""\n'
            )

    return 0


if __name__ == "__main__":
    sys.exit(main())
