"""Code emitter — turns the WIT IR into a Python module that wasmtime-py
accepts directly at the FFI boundary.

The emitter is single-pass over the type graph: every named type becomes one
Python class (record) or factory (variant/option/result). The emitted module
imports only ``wasmtime.component`` and depends on nothing from this package
at runtime — the generator can be lifted into wasmtime-py upstream as-is.

Wire-shape rules the emitted code obeys:

* **Records** expose kebab-case attributes. The Python ergonomic shim is
  snake_case via ``__init__`` parameters, but the underlying ``__dict__``
  uses kebab-case so wasmtime-py's ``getattr(val, "kebab-name")`` succeeds.
* **Enums** are ``str`` subclasses; their kebab-case spelling IS the value.
* **Variants** — see :mod:`bindgen._tagging`. Tagged: emit
  ``Variant(tag, payload)`` directly. Untagged: emit the bare payload, with
  the user choosing the arm by calling the right factory.
* **Options/Results** follow the same tagged/untagged classification.
* **Resources** get a thin Python wrapper that holds a
  ``ResourceAny``/``ResourceHost`` and exposes the WIT methods.

Code generation is deterministic: same WIT in, same Python out, byte-stable.
"""

from __future__ import annotations

import io
import textwrap

from . import _ir, _tagging
from ._ir import (
    Alias,
    Enum,
    Flags,
    Handle,
    List,
    Option,
    Record,
    Resolve,
    Resource,
    Result,
    Tuple,
    Type,
    TypeRef,
    Variant,
)


HEADER = '''\
"""Auto-generated by bindgen. Do not edit.

Wire-shape Python types for the WIT world. Constructed values are accepted
directly by wasmtime-py without further marshaling — kebab-case record
attributes, ``Variant(tag, payload)`` for tagged variants, raw payloads for
untagged ones.
"""

from __future__ import annotations

from typing import Any, Optional, Union

from wasmtime.component import Variant as _WitVariant


def ok(value: Any = None) -> _WitVariant:
    """Wrap ``value`` as the ``ok`` arm of a ``result<T, E>``.

    Always tagged on the wire because both arms can carry payloads — pass the
    bare ``value`` and this function lifts it into the right ``Variant``.
    """
    return _WitVariant("ok", value)


def err(value: Any = None) -> _WitVariant:
    """Wrap ``value`` as the ``err`` arm of a ``result<T, E>``."""
    return _WitVariant("err", value)
'''


def _snake(s: str) -> str:
    return s.replace("-", "_")


def _pascal(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in s.split("-"))


_PY_KEYWORDS = {
    "False", "None", "True", "and", "as", "assert", "async", "await", "break",
    "class", "continue", "def", "del", "elif", "else", "except", "finally",
    "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal",
    "not", "or", "pass", "raise", "return", "try", "while", "with", "yield",
}


def _ident(s: str) -> str:
    """Convert a kebab-case WIT name to a snake_case Python identifier,
    escaping reserved words by trailing-underscore."""
    snake = _snake(s)
    if snake in _PY_KEYWORDS:
        return snake + "_"
    return snake


def _type_name(t: Type, ir: Resolve) -> str:
    """Public Python class name for a named type."""
    assert t.name is not None
    return _pascal(t.name)


# --- Type expression ---------------------------------------------------

def _type_annotation(ref: TypeRef, ir: Resolve) -> str:
    """Render a Python type annotation for a TypeRef, used in __init__ signatures.

    For named types, uses the public class name. For containers, recurses.
    """
    if ref.is_primitive:
        return _PRIMITIVE_ANNOTATIONS[ref.primitive]
    canonical = ref.canonical(ir)
    if canonical.is_primitive:
        return _PRIMITIVE_ANNOTATIONS[canonical.primitive]
    t = ir.types[canonical.type_id]

    if t.name is not None:
        return _pascal(t.name)

    # Anonymous container types
    kind = t.kind
    if isinstance(kind, Option):
        inner = _type_annotation(kind.inner, ir)
        return f"Optional[{inner}]"
    if isinstance(kind, List):
        if kind.elem.is_primitive and kind.elem.primitive == "u8":
            return "bytes"
        elem = _type_annotation(kind.elem, ir)
        return f"list[{elem}]"
    if isinstance(kind, Tuple):
        elts = ", ".join(_type_annotation(t, ir) for t in kind.types)
        return f"tuple[{elts}]"
    if isinstance(kind, Result):
        return "Any"  # Results are encoded as Variant; user-facing form varies
    if isinstance(kind, Handle):
        return "Any"  # Resource handle — opaque
    return "Any"


_PRIMITIVE_ANNOTATIONS: dict[str, str] = {
    "bool": "bool",
    "s8": "int", "s16": "int", "s32": "int", "s64": "int",
    "u8": "int", "u16": "int", "u32": "int", "u64": "int",
    "f32": "float", "f64": "float",
    "char": "str",
    "string": "str",
}


def _wrap_field_for_storage(ty: TypeRef, value_expr: str, ir: Resolve, ctx: _tagging.TaggingCtx) -> str:
    """Return a Python expression that turns ``value_expr`` into the wire
    shape wasmtime-py expects when stored on a record's kebab-case attribute.

    Today the only adjustment is wrapping tagged options: an
    ``option<tagged-variant>`` (or anything whose inner contributes
    ``object`` to the case set) needs ``Variant('none' | 'some', payload)``
    on the wire. Untagged options pass ``None | payload`` through.
    """
    if ty.is_primitive:
        return value_expr
    canonical = ty.canonical(ir)
    if canonical.is_primitive:
        return value_expr
    target = ir.types[canonical.type_id]
    if isinstance(target.kind, Option) and _tagging.option_is_tagged(canonical, ctx):
        return f"(_WitVariant('none') if {value_expr} is None else _WitVariant('some', {value_expr}))"
    return value_expr


def _unwrap_field_for_read(ty: TypeRef, value_expr: str, ir: Resolve, ctx: _tagging.TaggingCtx) -> str:
    """Inverse of :func:`_wrap_field_for_storage` — if the field stores a
    wrapped option, return the bare ``None | payload`` form for snake-case
    accessor reads."""
    if ty.is_primitive:
        return value_expr
    canonical = ty.canonical(ir)
    if canonical.is_primitive:
        return value_expr
    target = ir.types[canonical.type_id]
    if isinstance(target.kind, Option) and _tagging.option_is_tagged(canonical, ctx):
        return f"(None if {value_expr}.tag == 'none' else {value_expr}.payload)"
    return value_expr


# --- Record emission ---------------------------------------------------

def _emit_record(t: Type, ir: Resolve, ctx: _tagging.TaggingCtx, out: io.StringIO) -> None:
    """Emit a record class with kebab-case attribute storage.

    The Python __init__ takes snake_case keyword args (so users call
    ``Foo(my_field=...)``); the underlying __dict__ uses kebab-case keys so
    wasmtime-py reads the right attribute via ``getattr(obj, "my-field")``.
    """
    assert isinstance(t.kind, Record)
    name = _type_name(t, ir)
    fields = t.kind.fields

    out.write(f"\nclass {name}:\n")
    if t.docs:
        out.write(f'    """{_format_docstring(t.docs)}"""\n')

    # No __slots__: Python identifier rules ban hyphens, and the kebab-case
    # attribute storage is what wasmtime-py reads via ``getattr(obj, "kebab-name")``.
    # The regular ``__dict__`` accepts any string key.

    # __init__ — snake_case args, kebab-case storage.
    if not fields:
        out.write("    def __init__(self) -> None:\n")
        out.write("        pass\n")
    else:
        out.write("    def __init__(\n")
        out.write("        self,\n")
        out.write("        *,\n")
        for f in fields:
            ann = _type_annotation(f.ty, ir)
            out.write(f"        {_ident(f.name)}: {ann},\n")
        out.write("    ) -> None:\n")
        for f in fields:
            # Store under the kebab-case name so wasmtime-py reads the right
            # attribute via ``getattr(obj, "kebab-name")``. If the field is a
            # tagged option, wrap on storage so wasmtime-py sees the right
            # ``Variant('none' | 'some', ...)`` shape.
            stored = _wrap_field_for_storage(f.ty, _ident(f.name), ir, ctx)
            out.write(f"        setattr(self, {f.name!r}, {stored})\n")

    out.write("\n")
    # Snake-case property accessors so Python users don't have to use
    # getattr (and so tagged-option fields read back as ``None | payload``,
    # not as the wrapped ``Variant`` form stored under the kebab attr).
    for f in fields:
        snake = _ident(f.name)
        unwrapped = _unwrap_field_for_read(f.ty, f"getattr(self, {f.name!r})", ir, ctx)
        if snake == f.name and unwrapped == f"getattr(self, {f.name!r})":
            continue  # plain attr access already works
        out.write(f"    @property\n")
        out.write(f"    def {snake}(self) -> {_type_annotation(f.ty, ir)}:\n")
        out.write(f"        return {unwrapped}\n\n")

    # __repr__ for ergonomics + __eq__ so round-trip tests can compare.
    out.write("    def __repr__(self) -> str:\n")
    if fields:
        parts = ", ".join(f"{_ident(f.name)}={{getattr(self, {f.name!r})!r}}" for f in fields)
        out.write(f"        return f'{name}({parts})'\n\n")
    else:
        out.write(f"        return '{name}()'\n\n")

    out.write("    def __eq__(self, other: object) -> bool:\n")
    out.write(f"        if not isinstance(other, {name}):\n")
    out.write("            return NotImplemented\n")
    if not fields:
        out.write("        return True\n")
    else:
        checks = " and ".join(
            f"getattr(self, {f.name!r}) == getattr(other, {f.name!r})" for f in fields
        )
        out.write(f"        return {checks}\n")

    out.write("\n    def __hash__(self) -> int:\n")
    out.write("        return id(self)\n")
    out.write("\n")


# --- Enum emission -----------------------------------------------------

def _emit_enum(t: Type, ir: Resolve, out: io.StringIO) -> None:
    """Emit an enum as a ``str`` subclass holding the kebab-case spelling.

    wasmtime-py's ``EnumType.convert_to_c`` expects a plain string of the
    case name. By making each enum a ``str`` subclass we keep type identity
    (``isinstance(MyEnum.FOO, MyEnum)`` works) without changing the wire
    representation — ``str(value)`` returns the kebab-case name unchanged.
    """
    assert isinstance(t.kind, Enum)
    name = _type_name(t, ir)

    out.write(f"\nclass {name}(str):\n")
    if t.docs:
        out.write(f'    """{_format_docstring(t.docs)}"""\n')
    out.write("    __slots__ = ()\n\n")

    for case in t.kind.cases:
        const = case.upper().replace("-", "_")
        if const in _PY_KEYWORDS:
            const += "_"
        out.write(f"    {const}: '{name}'\n")
    out.write("\n")

    # Materialize the constants after the class body using __new__ on str.
    for case in t.kind.cases:
        const = case.upper().replace("-", "_")
        if const in _PY_KEYWORDS:
            const += "_"
        out.write(f"{name}.{const} = {name}({case!r})  # type: ignore[attr-defined]\n")
    out.write("\n")


# --- Helpers -----------------------------------------------------------

def _format_docstring(text: str) -> str:
    """Normalize whitespace and escape any embedded ``\"\"\"`` for safe
    insertion between triple-quoted delimiters."""
    return textwrap.dedent(text).strip().replace('"""', '\\"\\"\\"')


# --- Variant emission --------------------------------------------------

def _emit_variant(t: Type, ir: Resolve, ctx: _tagging.TaggingCtx, out: io.StringIO) -> None:
    """Emit a variant as a namespace of factory functions, one per arm.

    Tagged variants:  ``MyVariant.arm(payload)`` returns ``Variant("arm", payload)``.
    Untagged:        ``MyVariant.arm(payload)`` returns the bare payload, and
                     ``MyVariant.unit_arm()`` returns ``None``.

    Either way the user picks the arm by calling the right factory; the
    returned value is what wasmtime-py expects on the wire.
    """
    assert isinstance(t.kind, Variant)
    name = _type_name(t, ir)
    cases = t.kind.cases
    tagged = _tagging.variant_is_tagged(_ir.TypeRef(type_id=t.id), ctx)

    out.write(f"\nclass {name}:\n")
    docs = (t.docs or "").strip()
    if docs:
        out.write(f'    """{_format_docstring(docs)}"""\n')
    note = (
        "Tagged variant: each arm wraps in ``Variant(tag, payload)``."
        if tagged
        else "Untagged variant: each arm returns its bare payload (or ``None`` for unit arms)."
    )
    out.write(f"    # {note}\n\n")

    for case in cases:
        ident = _ident(case.name)
        if case.ty is None:
            out.write(f"    @staticmethod\n")
            out.write(f"    def {ident}() -> Any:\n")
            if case.docs:
                out.write(f'        """{_format_docstring(case.docs)}"""\n')
            if tagged:
                out.write(f"        return _WitVariant({case.name!r})\n\n")
            else:
                out.write(f"        return None\n\n")
        else:
            ann = _type_annotation(case.ty, ir)
            out.write(f"    @staticmethod\n")
            out.write(f"    def {ident}(value: {ann}) -> Any:\n")
            if case.docs:
                out.write(f'        """{_format_docstring(case.docs)}"""\n')
            if tagged:
                out.write(f"        return _WitVariant({case.name!r}, value)\n\n")
            else:
                out.write(f"        return value\n\n")


# --- Flags / Tuples ----------------------------------------------------

def _emit_flags(t: Type, ir: Resolve, out: io.StringIO) -> None:
    """Flags are sets of strings on the wire — no class needed, but expose
    constants so users can write ``MyFlags.foo | MyFlags.bar`` style sets."""
    assert isinstance(t.kind, Flags)
    name = _type_name(t, ir)

    out.write(f"\nclass {name}:\n")
    if t.docs:
        out.write(f'    """{_format_docstring(t.docs)}"""\n')
    for flag in t.kind.names:
        const = flag.upper().replace("-", "_")
        if const in _PY_KEYWORDS:
            const += "_"
        out.write(f"    {const} = {flag!r}\n")
    if not t.kind.names:
        out.write("    pass\n")
    out.write("\n")


# --- Resource emission -------------------------------------------------

def _emit_resource(t: Type, ir: Resolve, out: io.StringIO) -> None:
    """Emit a wrapper around wasmtime-py's ``ResourceAny`` / ``ResourceHost``.

    Each WIT method on the resource becomes a Python method that delegates to
    ``self._invoke(wit_name, args)``. The runtime fills in ``._invoke`` (and
    ``._handle``) when constructing instances; the bindgen doesn't bind to a
    specific exported function because it has no view of which world the
    caller will instantiate.
    """
    assert isinstance(t.kind, Resource)
    name = _type_name(t, ir)

    # Find methods owned by this resource by scanning all interfaces and
    # finding functions whose ``kind`` is ``method`` / ``static`` / ``constructor``
    # with our ``id`` as the target.
    methods: list[tuple[str, _ir.Function]] = []
    for iface in ir.interfaces:
        for fn_name, fn in iface.functions.items():
            if fn.kind in ("method", "static", "constructor") and fn.resource == t.id:
                methods.append((fn.name, fn))

    out.write(f"\nclass {name}:\n")
    if t.docs:
        out.write(f'    """{_format_docstring(t.docs)}"""\n')
    out.write("    # Wraps a wasmtime-py ResourceAny / ResourceHost handle.\n")
    out.write("    # The runtime sets ._handle to the underlying resource and\n")
    out.write("    # ._invoke to a callable that dispatches a method by WIT name.\n\n")

    out.write("    def __init__(self, handle: Any, invoke: Any = None) -> None:\n")
    out.write("        self._handle = handle\n")
    out.write("        self._invoke = invoke\n\n")

    for raw_name, fn in methods:
        # Strip the WIT prefix to get the bare method name.
        if raw_name.startswith("[constructor]"):
            py_name = "new"  # surfaced as a static factory
        elif raw_name.startswith("[method]"):
            # "[method]agent.generate" -> "generate"
            py_name = _ident(raw_name.split(".", 1)[1])
        elif raw_name.startswith("[static]"):
            py_name = _ident(raw_name.split(".", 1)[1])
        else:
            py_name = _ident(raw_name)

        # Build the param list: skip the leading 'self' borrow for methods.
        params = fn.params[1:] if fn.kind == "method" else fn.params
        param_strs = [f"{_ident(p_name)}: {_type_annotation(p_ty, ir)}" for p_name, p_ty in params]
        ret_ann = _type_annotation(fn.result, ir) if fn.result is not None else "None"

        if fn.kind == "constructor":
            sig_args = ", ".join(param_strs)
            out.write(f"    @staticmethod\n")
            out.write(f"    def new({sig_args}, *, invoke: Any) -> '{name}':\n")
            arg_pass = ", ".join(_ident(p_name) for p_name, _ in params)
            out.write(
                f"        return {name}(invoke('[constructor]{t.name}', ({arg_pass},)), invoke)\n\n"
            )
        elif fn.kind == "static":
            sig_args = ", ".join(param_strs)
            out.write(f"    @staticmethod\n")
            out.write(f"    def {py_name}({sig_args}, *, invoke: Any) -> {ret_ann}:\n")
            arg_pass = ", ".join(_ident(p_name) for p_name, _ in params)
            out.write(f"        return invoke('[static]{t.name}.{raw_name.split('.', 1)[1]}', ({arg_pass},))\n\n")
        else:  # method
            sig_args = "self" + ("" if not param_strs else ", " + ", ".join(param_strs))
            out.write(f"    def {py_name}({sig_args}) -> {ret_ann}:\n")
            arg_pass = ", ".join(_ident(p_name) for p_name, _ in params)
            arg_tuple = f"(self._handle, {arg_pass},)" if arg_pass else "(self._handle,)"
            out.write(f"        return self._invoke('[method]{t.name}.{raw_name.split('.', 1)[1]}', {arg_tuple})\n\n")

    if not methods:
        out.write("    pass\n\n")


# --- Module-level driver ----------------------------------------------

def emit_module(ir: Resolve) -> str:
    """Render the full Python module for the given WIT IR.

    Output is deterministic — types are emitted in IR (i.e. type-id) order so
    the same input always produces byte-identical output.
    """
    out = io.StringIO()
    out.write(HEADER)
    out.write("\n")

    ctx = _tagging.TaggingCtx.new(ir)

    for t in ir.types:
        if t.name is None:
            continue  # anonymous container types are emitted inline by _type_annotation
        if isinstance(t.kind, Record):
            _emit_record(t, ir, ctx, out)
        elif isinstance(t.kind, Enum):
            _emit_enum(t, ir, out)
        elif isinstance(t.kind, Variant):
            _emit_variant(t, ir, ctx, out)
        elif isinstance(t.kind, Flags):
            _emit_flags(t, ir, out)
        elif isinstance(t.kind, Resource):
            _emit_resource(t, ir, out)
        elif isinstance(t.kind, Alias):
            # `use other.{this-name}` — emit a Python alias unless the target
            # already shares this name (in which case it's already bound).
            target = t.kind.target.canonical(ir)
            if target.is_primitive:
                continue
            target_t = ir.types[target.type_id]
            if target_t.name is None or target_t.name == t.name:
                continue
            out.write(f"\n{_type_name(t, ir)} = {_type_name(target_t, ir)}\n")

    return out.getvalue()


__all__ = ["emit_module"]
