name: "wasmtime-py: CI"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: wasmtime-py-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: wasmtime-py
    steps:
      - uses: actions/checkout@v4
      - uses: ./wasmtime-py/.github/actions/setup
      - run: uv run --all-extras pytest

  coverage:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: wasmtime-py
    steps:
      - uses: actions/checkout@v4
      - uses: ./wasmtime-py/.github/actions/setup
      - run: uv run --all-extras coverage run -m pytest
      - run: uv run --all-extras coverage html
      - uses: actions/upload-artifact@v4
        with:
          name: wasmtime-py-coverage
          path: wasmtime-py/htmlcov

  build-wheel:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: wasmtime-py
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch history & tags so setuptools-git-versioning can generate a
          # unique .devN suffix on untagged builds uploaded to test.pypi.org.
          # See `tool.setuptools-git-versioning` in `pyproject.toml`.
          fetch-depth: 0
      - uses: ./wasmtime-py/.github/actions/setup
      - run: pip install build
      - name: Build sdist
        run: |
          git clean -fdx wasmtime build
          python -m build --sdist
      - name: Build wheel (macOS arm64)
        run: |
          git clean -fdx wasmtime build
          python -m build --wheel -C=--build-option=--plat-name -C=--build-option=macosx-11-0-arm64
      - uses: actions/upload-artifact@v4
        with:
          name: wasmtime-py-dists
          path: wasmtime-py/dist
